package com.sonabel.cmt.enums;

public enum TypeNotification {
    NOUVELLE_RESERVATION,
    RESERVATION_VALIDEE,
    RESERVATION_REFUSEE,
    RESERVATION_ANNULEE,
    RAPPEL_SEJOUR,
    COMPTE_APPROUVE,
    COMPTE_REJETE,
    NOUVELLE_DEMANDE_INSCRIPTION,
    PAYEMENT_CONFIRME
}
